export enum ROUTES {
  HOME = 'HOME',
  RECIPE = 'RECIPE',
  ALL_RECIPES = 'ALL_RECIPES',
  ALL_INGREDIENTS = 'ALL_INGREDIENTS',
  CREATE_RECIPE = 'CREATE_RECIPE',
  CREATE_INGREDIENT = 'CREATE_INGREDIENT',
  SEARCH_RESULT = 'SEARCH_RESULT'
}
